version: "3.8"

services:
  postgres:
    image: postgres:16.4
    container_name: stacks-db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: stacks
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  test-postgres:
    image: postgres:16.4
    container_name: test-stacks-db
    restart: always
    environment:
      POSTGRES_USER: test_admin
      POSTGRES_PASSWORD: test_admin
      POSTGRES_DB: test_stacks
    ports:
      - "5433:5432"
    volumes:
      - test_postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
  test_postgres_data:
    driver: local
