BASE_URL = "https://www.saltedge.com/api/v5"
PROVIDERS_URL = "https://www.saltedge.com/api/v5/providers"
CUSTOMERS_URL = "https://www.saltedge.com/api/v5/customers"
CONNECT_SESSIONS_URL = "https://www.saltedge.com/api/v5/connect_sessions"
CONNECTIONS_URL = "https://www.saltedge.com/api/v5/connections"
ACCOUNTS_URL = "https://www.saltedge.com/api/v5/accounts"
TRANSACTIONS_URL = "https://www.saltedge.com/api/v5/transactions"
